openapi: 3.1.0
info:
  title: Bazar space openapi
  version: v1
paths:
  /space:
    get:
      tags:
        - space-controller
      operationId: getAllSpaces
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/GetSpacesResponse"
    post:
      tags:
        - space-admin-controller
      operationId: createSpace
      parameters:
        - in: query
          name: name
          description: space name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: '#/components/schemas/GetSpaceDto'
  /space/user:
    post:
      tags:
        - space-admin-controller
      operationId: addUserToSpace
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddUserToSpaceDtoRequest"
        required: true
      responses:
        "200":
          description: OK
  /space/{spaceId}/user:
    get:
      tags:
        - space-controller
      operationId: getAllUsersInSpace
      parameters:
        - name: spaceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: string
                  format: uuid
  /space/{spaceId}:
    delete:
      tags:
        - space-admin-controller
      operationId: deleteSpace
      parameters:
        - name: spaceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
    patch:
      tags:
        - space-admin-controller
      operationId: patchSpace
      parameters:
        - name: spaceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/GetSpaceDto"
  /space/{spaceId}/user/{userId}:
    delete:
      tags:
        - space-admin-controller
      operationId: deleteUserFromSpace
      parameters:
        - name: spaceId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: OK
components:
  schemas:
    AddUserToSpaceDtoRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        spaceId:
          type: integer
          format: int64
      required:
        - userId
        - spaceId
    GetSpaceDto:
      description: space info for get requests
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string

    GetSpacesResponse:
      type: object
      properties:
        spaces:
          type: array
          items:
            $ref: '#/components/schemas/GetSpaceDto'
