spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bzruathz}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  jpa:
    show-sql: true
  grpc:
    client:
      default-channel:
        address: ${BAZAR_AUTHORIZATION_GRPC_URL:localhost:9090}
  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KC_URL:http://localhost:9999}/realms/${KC_REALM:bazar-realm}
  threads:
    virtual:
      enabled: true
server:
  servlet:
    context-path: /api
  port: 8080
management:
  server:
    port: 8090
logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL:DEBUG}