spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    change-log: db/changelog/changelog-master.yaml
  jpa:
    show-sql: true
  grpc:
    client:
      default-channel:
        address: ${BAZAR_AUTHORIZATION_GRPC_URL}
  security:
    oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${KC_EXTERNAL_URL}/realms/${KC_REALM}
            jwk-set-uri: ${KC_URL}/realms/${KC_REALM}/protocol/openid-connect/certs
server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      bazar: ${LOGGING_LEVEL}